### ISSUE TITLE
Make New Wiki Button from within TW5 fails

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#14]
This is great Jedediah!  Very cool stuff.  This makes me increasingly more optimistic about using TW5 with my team.  Thank you very much for the very clear and helpful response.

I have a follow-up question regarding my e-mail to you earlier.  As I  began playing with the "starting other wiki" tid.  I tried to test making a "make new wiki button" and even though there is a:

```
"scripts": {
    "NewWiki":  "tiddlywiki #wikiName --init #editionName" 
}
```

script already in my Node Settings, it's seems to crash when I click it.  

I observed your note:  

_**Note:** This does not create the wiki. If the wiki doesn't exist this won't do anything. To create a new wiki from within the wiki see the example for the runScript message._

when I attempt the runScript example:

```
<$button>
  Make Wiki!
  <$action-websocketmessage $type='runScript' name='NewWiki' #wikiName='Wikis/SomeName' #editionName='MultiUser'/>
</$button>
```

it fails with the following error:

```
For Test Make Wiki Button, type is application/x-tiddler hasMetaFile is false filepath is /home/sean/TiddlyWiki5/editions/MultiUserWiki/tiddlers/Test Make Wiki Button.tid
saved file /home/sean/TiddlyWiki5/editions/MultiUserWiki/tiddlers/Test Make Wiki Button.tid
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: spawn tiddlywiki ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by inmysocks** [comment]
That error means that it can't find the tiddlywiki command. If you don't have tiddlywiki installed globally it won't work.

You can try replacing

tiddlywiki

with 

node ./tiddlywiki.js

in the command and that should work.

**Comment by sb3rg** [comment]
So, I installed tiddlywiki globally and it seems to have stopped the above error.  However now it shows that it cannot find the edition.  I tried changing the edition name to "MultiUserWiki", boo, but that did not work.  Any suggestions?

`Error: Edition 'MultiUser' not found`

**Comment by inmysocks** [comment]
See the instructions about how to set up the editions location on tiddlywiki.com https://tiddlywiki.com/#Environment%20Variables%20on%20Node.js

There are more specific instructions about this on the readme of the repo under the manual instructions.

This is just running a shell command from inside tiddlywiki. Any problems would be handled the same as if you got them when running the command from a terminal.

**Comment by sb3rg** [comment]
@inmysocks, it may be more clear if the example used "MultiUserWiki" instead of just "MultiUser" so future users don't have to modify that to play with the example.  Just a suggestion.  Thank you for all of your help!
