### ISSUE TITLE
Correct way to update without wipping out all my sub-wikis

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#21]
When I perform: `git pull origin master` in the MultiUser folder, then copy to "TiddlyWiki5/editions" it erases all wikis located in the Node JSON settings.  Suggestions for how to properly update MultiUser without erasing all my wiki JSON references?

**Comment by inmysocks** [comment]
Just don't copy over your wiki.

I think you are talking about pulling the changes into the MultiUser plugin folder, which updates the plugin. If you are copying things into the editions folder than you are writing over them. There isn't any reason to do that and the result is that you are overwriting your files and losing any changes.

It is probably also a good idea to not have a wiki you work on in the editions folder.

**Comment by sb3rg** [comment]
Oh ok! I'll try that.  It seems, though, that the default location for wikis creating the "New Wiki" button is defaulted to the editions folder.
