### ISSUE TITLE
Image/File Management

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#25]
I know this is not exactly an issue with MultiUser per se, but it's become evident that TiddlyWiki nodejs version is limited in file/image management.  If I can't fix this problem with the use of the MultiUser edition of TW, then we will have to start looking for other Wiki platform options (and I'd much prefer to use TW, if possible)

My issue is we do not have the ability to load images or files more generally to the wiki.  I have tried:

1. dragging images into the wiki --> Did not upload to node server
2. creating external links to network shared images using _canonical_uri --> does not load the image even when I add a browser plug-in to enable local-file links

Do you have any suggestions on how you manage files and images to Tiddlywiki be it directly loading them onto your server or using canonical links?  I think you mentioned using TW MultiUser for your own teams.  Do ya'll simply not use the wiki for files/images? Or, do you have a special process in place for uploading them?

**Comment by inmysocks** [comment]
Are you using the newest version?

On the wikis I am using I can just drag and drop the images into the wiki and they are saved like on the normal nodejs version. Or if you want to use _canonical_uri  you can set the filePathRoot in the settings.json

https://github.com/OokTech/TW5-MultiUser/blob/master/Configuration.md

**Comment by sb3rg** [comment]
I updated to the newest versions of both TW5 and MultiUserWiki.  It looks like with this change the drag and drop feature now imports files.  

For the _canonical_uri feature, I couldn't confirm whether it works.  Here is what I did.

1.  added "path":"file://milwaukee/project/MASTERS/Data%20Science/ds_imgs" manually to the settings.json.
2.  I restarted the server to make sure settings.json was loaded
3.  I confirmed that "file://milwaukee/project/MASTERS/Data%20Science/ds_imgs" is indeed network accessible via browser.
4.  I created an image tiddler with _canonical_uri set to "path/my_image.png"

It shows this:
![image](https://user-images.githubusercontent.com/4951467/39841823-b887c810-53a9-11e8-90a6-394b8c77f5e1.png)

My guess is that I am not properly accessing the path from settings.json?

**Comment by sb3rg** [comment]
the record has to specifically be named "filePathRoot"?  I just gave it an arbitrary name.

**Comment by inmysocks** [comment]
The specifics are here.

https://github.com/OokTech/TW5-MultiUser/blob/master/Configuration.md

https://github.com/OokTech/TW5-MultiUser/blob/master/Documentation/Serving%20Files.tid

**Comment by sb3rg** [comment]
Got it.  Thank you for pointing me to the Serving Files documentation.  That helped me understand the importance of using specifically "filePathRoot" as the key in settings.json.  Unfortunately, when using 
"./file/my_image.png" for my _canonical_uri and setting the tiddler type to ''image/png,"  It for some reason still does not work, 

I attempted to change filePathRoot from:
`file://milwaukee/project/MASTERS/Data Science/ds_imgs`
to
`file:///milwaukee/project/MASTERS/Data Science/ds_imgs`

I tried both with backslashes as well restarting the server after each change and none of those worked either

I am satisfied for now with just importing the images directly so you can close this issue, but I'm just letting you know I was never able to get it to work using _canonical_uri =/

Thank you for your help!!

**Comment by inmysocks** [comment]
If you just use the file path to the folder like in examples in the documentation instead of the full uri with the scheme it should work fine.

File paths start with / on linux or osx and something like c:/ on windows. uris start with file:///
