### ISSUE TITLE
Configure port number listened by the websocket in setting file

### ISSUE THREAD

**Issue by a3785lex** [OokTech/TW5-MultiUser#4]
First of all, many thanks to you for developing this super awesome plug-in. I have been searching for how to co-work on TiddlyWiki for quite some time and this plug-in totally solves my problem. Not to mention that the auto-saving functionality comes with it is also very handy.
Now I am trying to host a TiddlyWiki server with this plug-in in a docker container. I have to determine which ports to expose from the container for the server to work correctly. However I find that although I can configure the serving port in the `settings.json`, but I cannot find a place to configure the listening port. Is it possible to configure it or currently is it safe to assume that it will always be the serving port + 1?

**Comment by a3785lex** [comment]
Thanks a lot for your reply. I think in my use case it is good enough for me to know that the port number will be next open port greater than the server port. I opened this issue simply because I was curious if there is a way to configure it but not really wanted to request for such a feature if it is not possible. So please feel free to close issue if you would like to.

**Comment by inmysocks** [comment]
This should be implemented now. In the settings.json file if you set 'autoincrementPort' to false under 'ws-server' than the web socket server port will be the one above the wiki port and the process will fail if the port is in use.

By default (if the entry is missing in the settings file) than the server will use the next open port. The example settings file has it set to false to show where the setting is.

This does mean that while that is set you will have to manually list the ports in the configuration files for any child wikis you start that have the multi-user plugin active.

**Comment by dasBuero** [comment]
@a3785lex May I ask you for your docker setup with TiddlyWiki and Bob Plugin? I'm struggling with setting up my own.

BTW Thank you for this wonderful plugin Jed and sorry for hijacking an old thread :grimacing:

**Comment by inmysocks** [comment]
I don't use docker. In the future.make a new issue, don't make unrelated commments on old issues.
