### ISSUE TITLE
Issue when trying to set filePathRoot with relative path

### ISSUE THREAD

**Issue by laurentbonet** [OokTech/TW5-MultiUser#68]
Hello,

I read in the documentation that relative path were possible for filePathRoot

_'Note:'' All paths can be either absolute or relative. Relative paths are relative to the folder with tiddlywiki.js in it if you are using the plugin version or the folder with the executable file if you are using the BobEXE version.

''Note for windows:'' All the example paths here are how they would appear on linux or osx. On windows the paths would look like C:\Users\inmysocks\TiddlyWiki\Wikis. To make the examples what you would use in windows replace /home with C:\Users and change the / into \._

When trying to have path like ."/Wikis" or "Wikis" either through the UI or directly modifying settings.json I'm getting an error message (see hereafter) and $__WikiSettings.tid is not updated.
By the way stuff is working correctly even when entering an absolute path (even if this path does not exist on my file system)

PS1: Congratulation for the job you are doing on Bob !!!

WebSocket error, probably closed connection:  TypeError: Cannot read property 'RootWiki' of undefined
    at Object.$tw.CreateSettingsTiddlers ($:/plugins/OokTech/NodeSettings/NodeSettings.js:121:18)
    at Object.$tw.nodeMessageHandlers.browserTiddlerList ($:/plugins/OokTech/Bob/NodeMessageHandlers.js:47:9)
    at WebSocket.$tw.Bob.handleMessage ($:/plugins/OokTech/Bob/NodeWebSocketsSetup.js:157:50)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage ($:/plugins/OokTech/Bob/External/WS/lib/websocket.js:720:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:415:14)
    at Receiver.getData ($:/plugins/OokTech/Bob/External/WS/lib/receiver.js:347:17)
new connection

Make sure you read contributing.md and check the correct boxes below and then
add your issue text here.
If you don't than the issue will be tagged as spam and closed or deleted.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [x] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by TiddlyTweeter** [comment]
This is my impression too. That the pathing for "filePathRoot" currently has to be absolute; relative does  not seem to work. Otherwise Bob is fully portable.

I'm on Bob.EXE on Windows 7 in Firefox 52 ESR, both 64.
