### ISSUE TITLE
I believe you have the wrong copy for line 3 under new TW setup

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#7]
cp -r TiddlyWiki5/plugins/OokTech/**TW5-**MultiUser/MultiUserWiki TiddlyWiki5/editions/

SHOULD BE:
cp -r TiddlyWiki5/plugins/OokTech/MultiUser/MultiUserWiki TiddlyWiki5/editions/

Am I wrong in this?  If I copy and run the first two lines, I'm only left with "MultiUser" folder under OokTech.

**Comment by sb3rg** [comment]
_Correction:_

To get it to work i actually had to change line 2:
from:  git clone --depth=1 https://github.com/OokTech/TW5-MultiUser.git TiddlyWiki5/plugins/OokTech/MultiUser

to:  git clone --depth=1 https://github.com/OokTech/TW5-MultiUser.git TiddlyWiki5/plugins/OokTech/**TW5-**MultiUser

**Comment by inmysocks** [comment]
You are correct, but I went with the first version and changing the other parts that need to be changed (the listing in the tiddlywiki.info file needs to have the TW5- removed also.)

For the moment the plugin name needs to be consistent so removing the TW5- prefix works better.

Thank you for pointing this out!

**Comment by sb3rg** [comment]
No problem!  Thanks for making this awesome plugin!

**Comment by sb3rg** [comment]
as a side question, any chance you know how to keep saving changes from downloading the wiki file?  I only want it to persist on the server but it keeps sending me a tiddlywiki.html

**Comment by inmysocks** [comment]
The answer is maybe, but I will make a new issue for it and close this one.
