### ISSUE TITLE
Duplicating Tiddlers?

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#8]
This plugin seems to duplicate all of my tiddlers on server restart.  For example, if I create a tiddler called "Contents" and restart the node server, the wiki will now have another duplicate tiddler called "{}Contents" that I have to then manually delete.  I tested this with a TW with dozens of tids and it duplicated all of them.

**Comment by inmysocks** [comment]
I had this problem before but I thought it was fixed. So I have a few questions to help me find out what is going on:

When was the last time you updated the plugin?
Are the tiddlers saved as files or show up in the wiki also?
What operating system are you using?

**Comment by sb3rg** [comment]
I believe I downloaded the plugin Monday the 5th of March.  I haven't updated it since.  

I'll check the folder on the server to see if actual files are being saved in duplicate.  When I relaunch the server, I see a lot of "renaming..." lines printing.  I'll try to get you an example of a feed when I get to the office.

I'm using Arch Linux, the latest version as of Sunday of this week.

**Comment by sb3rg** [comment]
Is it possible that you pushed an older branch by accident?  I recall last week when playing with this that I was able to copy the 3 step multiuser installation steps without having to change the folder names from "MultiUser" to "TW5-MultiUser."  But this week is when I ran into that hiccup.  This could explain why before it worked, but not it's not?  I hope that helps.

**Comment by inmysocks** [comment]
The newest version is from two days ago, so try that. Also you need the folders to be named MultiUser, not TW5-MultiUser now. That is why the instructions were updated. This would also keep it from being able to save.

**Comment by sb3rg** [comment]
Yes, this fixed the errors I was encountering.
