### ISSUE TITLE
Prevent save from downloading an html file

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-MultiUser#9]
From @sb3rg in #7 

> any chance you know how to keep saving changes from downloading the wiki file? I only want it to persist on the server but it keeps sending me a tiddlywiki.html

**Comment by inmysocks** [comment]
Changes are saved to the server automatically as soon as possible, so the save button doesn't have any useful function other than as a dirty indicator (to show that there are unsaved changes). Because of that I left it so that it would download the html file.

I should be able to put a setting somewhere that lets you disable the download behaviour. I will add it to the list.

**Comment by sb3rg** [comment]
When testing it, I see the indicator auto save by being red during editing and the going back to neutral state, but when I exit the browser (Chrome), and reopen my port, none of the changes are saved.  I've been finding that I have actually click the "save" button and thereby download html in order for saves to actually perform.

**Comment by inmysocks** [comment]
I haven't been able to duplicate this behaviour.

**Comment by sb3rg** [comment]
I moved the latest version.  I think some of the errors had to do with changing the name to TW5-MultiUser instead of just MultiUser.  Now everything seems to be working smoothly.  Thank you!
